name: 'Repository Dispatch'
description: 'Generate a repository dispatch event'
author: 'Defold'
inputs:
  owner:
    description: 'Repository owner'
  repo:
    description: 'Repository name'
  token:
    description: 'GitHub authorization token'
  action:
    description: "Event action"
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.token }}
    - ${{ inputs.action }}
