name: 'Repository Dispatch'
description: 'Generate a repository dispatch event'
author: 'Defold'
inputs:
    repo:
        description: 'Repository to dispatch event to'
    token:
        description: 'GitHub authorization token'
    user:
        description: 'GitHub user to which the authentication token belongs'
    action:
        description: "Event action"
runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.repo }}
        - ${{ inputs.token }}
        - ${{ inputs.user }}
        - ${{ inputs.action }}
